version: '3.8'

services:
  web:
    build:
      context: .
    tty: true
    command: gunicorn --bind 0.0.0.0:8000 antibot.wsgi
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
